openapi: 3.0.3
info:
  title: Random coffee
  description: Random coffee
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /login:
    post:
      summary: Logs in and returns the authentication cookie
      operationId: userLogin
      requestBody:
        required: true
        description: A JSON object containing the login and password.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      security: [ ]
      responses:
        '200':
          description: >
            Successfully authenticated.
            The session ID is returned in a cookie named `SESSION_ID`. You need to include this cookie in subsequent requests.
          headers:
            Set-Cookie:
              schema:
                type: string
                example: SESSION_ID=abcde12345; Path=/; HttpOnly
        '400':
          description: Invalid login or password
  /logout:
    post:
      summary: Deletes current user session
      operationId: userLogout
      security:
        - CookieAuth: [ ]
      responses:
        '401':
          description: possibly missing session id cookie or it is invalid
        '200':
          description: session deleted
  /register:
    post:
      summary: Registers a new website user
      operationId: userRegister
      requestBody:
        required: true
        description: A JSON object containing essential user data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      security: [ ]
      responses:
        '200':
          description: >
            Successfully registered
            You now may proceed to login form
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: >
            Specified data is invalid, possibly trying to register existing login 
  /users/{id}:
    get:
      tags:
        - Users
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The user id
      summary: Retrieves current user information
      operationId: getUser
      security:
        - CookieAuth: [ ]
      responses:
        '403':
          description: Current user doesn't have permissions to see this user profile
        '401':
          description: Missing session id in request
        '200':
          description: Successfully get user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/me:
    patch:
      tags:
        - Users
      summary: Update user information
      operationId: updateMyProfile
      security:
        - CookieAuth: [ ]
      requestBody:
        required: true
        description: New fields to user
        content:
          application/jpeg:
            schema:
              $ref: '#/components/schemas/PatchUser'
      responses:
        '403':
          description: Not authed
        '400':
          description: Incorrect params
        '200':
          description: Successfully get user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    get:
      tags:
        - Users
      summary: Retrieves current user information
      operationId: getMyProfile
      security:
        - CookieAuth: [ ]
      responses:
        '401':
          description: Missing session id in request
        '200':
          description: Successfully get user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /user_pics/{id}:
    get:
      tags:
        - Users
      summary: Get list of links to user-pics
      operationId: GetUserPic
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            minLength: 5
          description: The avatar id
      responses:
        '200':
          description: >
            bytes of the avatar
          content:
            application/jpeg:
              schema:
                $ref: '#/components/schemas/RawImage'
        '404':
          description: img not found
  /users/me/user_pics:
    post:
      tags:
        - Users
      summary: Add photo to user profile
      operationId: AddPhoto
      requestBody:
        required: true
        description: Raw data for image
        content:
          application/jpeg:
            schema:
              $ref: '#/components/schemas/RawImage'
      security:
        - CookieAuth: [ ]
      responses:
        '201':
          description: >
            Image successfully added to user profile
        '403':
          description: Current user doesn't have permissions to edit this user profile
        '401':
          description: Missing session id in request
  /users/me/clubs:
    get:
      tags:
        - Users
      summary: Get list user's clubs
      operationId: GetUserClubs
      security:
        - CookieAuth: [ ]
      responses:
        '200':
          description: clubs and you with club
          content:
            application/jpeg:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserClub'
        '403':
          description: Current user doesn't have permissions
        '401':
          description: Missing session id in request
  /users/me/contacts:
    get:
      tags:
        - Users
      summary: Get list user's contacts
      operationId: GetUserContacts
      security:
        - CookieAuth: [ ]
      responses:
        '200':
          description: Get contacts of user
          content:
            application/jpeg:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserContact'
        '403':
          description: Current user doesn't have permissions
        '401':
          description: Missing session id in request
  /users/me/clubs/{id}:
    post:
      tags:
        - Clubs
      summary: Subscribe current user to club
      operationId: AddUserToClub
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minLength: 5
          description: id of new club
      security:
        - CookieAuth: [ ]
      responses:
        '201':
          description: >
            You added to the club
        '403':
          description: Current user doesn't have permissions
        '401':
          description: Missing session id in request
        '400':
          description: Club not found
    delete:
      tags:
        - Users
      summary: Unsubscribe current user to club
      operationId: RemoveUserFromClub
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minLength: 5
          description: id of club
      security:
        - CookieAuth: [ ]
      responses:
        '200':
          description: >
            You removed from club
        '403':
          description: Current user doesn't have permissions
        '401':
          description: Missing session id in request
        '400':
          description: Club not found
  /clubs:
    post:
      summary: Build new club
      operationId: addNewClub
      requestBody:
        required: true
        description: A JSON object containing club data
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewClub'
      responses:
        '200':
          description: >
            clubs gotten
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Club'
        '400':
          description: >
            Specified data is invalid
    get:
      summary: Get list of clubs
      operationId: getClubs
      responses:
        '200':
          description: >
            club gotten
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Club'
        '400':
          description: >
            Specified data is invalid
  /clubs/{id}:
    delete:
      tags:
        - Clubs
      summary: Delete club
      operationId: DeleteClubById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The club-id
      responses:
        '200':
          description: >
            club delete
        '404':
          description: club not found
    get:
      tags:
        - Clubs
      summary: Get club
      operationId: GetClubById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The club-id
      responses:
        '200':
          description: >
            club info
          content:
            application/jpeg:
              schema:
                $ref: '#/components/schemas/Club'
        '404':
          description: club not found
  /clubs/{id}/pic:
    get:
      tags:
        - Clubs
      summary: Get club logo
      operationId: GetClubPic
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: The club-id
      responses:
        '200':
          description: >
            bytes of the avatar
          content:
            application/jpeg:
              schema:
                $ref: '#/components/schemas/RawImage'
        '404':
          description: img not found
    post:
      summary: Add new photo to club
      operationId: AddPhotoToClub
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: id of club
      requestBody:
        required: true
        description: Raw data for image
        content:
          application/jpeg:
            schema:
              $ref: '#/components/schemas/RawImage'
      security:
        - CookieAuth: [ ]
      responses:
        '201':
          description: >
            Image successfully added
  /contacts:
    post:
      summary: Generate a new meeings round for a given period
      operationId: GenerateContactsRound
      parameters:
        - in: query
          name: date
          required: true
          schema:
            type: string
            format: date
          description: A day for generating meetings
      responses:
        '400':
          description: Invalid meeting period
        '201':
          description: >
            Meetings created
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    CookieAuth:
      type: apiKey
      in: cookie
      name: SESSION_ID
  schemas:
    LoginRequest:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
          example: aa1limonov
        password:
          type: string
          example: top-secret
    RegisterRequest:
      type: object
      required:
        - login
        - password
        - tg_login
        - city
        - first_name
        - last_name
        - email
      properties:
        login:
          type: string
        password:
          type: string
        tg_login:
          type: string
        city:
          type: string
        first_name:
          type: string
          example: Alexey
        last_name:
          type: string
          example: Limonov
        email:
          type: string
          example: aalimonov_2@miem.hse.ru
    User:
      type: object
      required:
        - id
        - email
        - login
        - first_name
        - last_name
        - tg_login
        - avatar
        - city
        - interests
      properties:
        id:
          type: integer
        email:
          type: string
          example: aalimonov_2@miem.hse.ru
        login:
          type: string
          example: aalimonov_2
        first_name:
          type: string
          example: Alexey
        last_name:
          type: string
          example: Limonov
        tg_login:
          type: string
          example: '@olexvp'
        avatar:
          type: string
        city:
          type: string
        interests:
          type: array
          items:
            type: string
            example: Coffee
    PatchUser:
      type: object
      properties:
        email:
          type: string
          example: aalimonov_2@miem.hse.ru
        login:
          type: string
          example: aalimonov_2
        first_name:
          type: string
          example: Alexey
        last_name:
          type: string
          example: Limonov
        tg_login:
          type: string
          example: '@olexvp'
    UserClub:
      type: object
      required:
        - id
        - name
        - description
        - occupation
        - is_subscribed
        - image_url
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'ИВТ МИЭМ'
        occupation:
          type: string
          example: 'Москва'
        is_subscribed:
          type: boolean
        description:
          example: 'Встречи со студентами и выпускниками ИВТ МИЭМ'
          type: string
        image_url:
          type: string
          example: 'https://rndcfe.ru/clubs/1/pic'
    NewClub:
      type: object
      required:
        - name
        - description
        - occupation
      properties:
        name:
          type: string
          example: 'ИВТ МИЭМ'
        occupation:
          type: string
          example: 'Москва'
        description:
          type: string
          example: 'Москва'
    Club:
      type: object
      required:
        - id
        - name
        - description
        - occupation
        - imag_url
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'ИВТ МИЭМ'
        occupation:
          type: string
          example: 'Москва'
        description:
          type: string
          example: 'Москва'
        image_url:
          type: string
          example: 'https://rndcfe.ru/clubs/1/pic'
    PatchClub:
      type: object
      required:
        - name
        - description
        - occupation
      properties:
        name:
          type: string
          example: 'ИВТ МИЭМ'
        description:
          type: string
          example: 'ИВТ МИЭМ'
        occupation:
          type: string
          example: 'Москва'
    UserContact:
      type: object
      required:
        - id
        - user_id
        - user_name
        - occupation
        - time
        - avatar_url
      properties:
        id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 12
        user_name:
          type: string
          example: Арвок Векукерин
        occupation:
          type: string
          example: 'Строгино'
        time:
          type: string
          format: date-time
        avatar_url:
          type: string
          example: 'https://rndcfe.ru/clubs/1/pic'
    RawImage:
      type: string
      format: binary
